'use strict';
const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const browser = await chromium.launch({ headless: true, ...(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {}) });
  try {
    const context = await browser.newContext({ viewport: { width: 1280, height: 1000 } });
    const page = await context.newPage(); const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(process.env.APP_URL || 'http://127.0.0.1:8765');
    await page.locator('#keywords').fill('annual report');
    await page.locator('#scope').fill('example.com, docs.example.com');
    await page.locator('#exact').fill('public data');
    const expected = '(site:example.com OR site:docs.example.com) (annual report "public data")';
    assert.equal(await page.locator('#outputBox').innerText(), expected);
    await page.locator('#saveName').fill('Araştırma'); await page.locator('#saveBtn').click();
    await page.reload(); assert.equal(await page.locator('#outputBox').innerText(), expected);
    await page.locator('[data-tab="library"]').click(); assert.match(await page.locator('#savedList').innerText(), /Araştırma/);
    await page.locator('#savedList').getByRole('button', { name: 'aç', exact: true }).click();
    assert.equal(await page.locator('#scope').inputValue(), ''); assert.equal(await page.locator('#customInput').inputValue(), expected);
    await page.locator('#customInput').fill('site:example.com "report');
    assert.match(await page.locator('#diagnostics').innerText(), /tırnak/);
    await page.locator('#clearBtn').click(); assert.equal(await page.locator('#customInput').inputValue(), '');
    assert.equal(await page.locator('#searchBtn').isDisabled(), true);
    await page.locator('#customInput').fill('filetype:pdf "rapor & veri"');
    await page.locator('#engine').selectOption('bing');
    await page.evaluate(() => { window.open = (url, target, features) => { window.testOpened = {url, target, features}; }; });
    await page.locator('#searchBtn').click();
    const opened = await page.evaluate(() => window.testOpened);
    assert.equal(new URL(opened.url).hostname, 'www.bing.com'); assert.equal(new URL(opened.url).searchParams.get('q'), 'filetype:pdf "rapor & veri"'); assert.equal(opened.features, 'noopener,noreferrer');
    await page.locator('[data-tab="library"]').click(); assert.match(await page.locator('#historyList').innerText(), /rapor & veri/);
    const before = await page.locator('#savedList .dork-item').count();
    await page.locator('#importFile').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({version:1, records:[{name:'valid',query:'report'}, {name:'invalid',query:3}]})) });
    await page.waitForFunction(() => document.getElementById('status').textContent.startsWith('İçe aktarılamadı'));
    assert.equal(await page.locator('#savedList .dork-item').count(), before);
    await page.locator('#importFile').setInputFiles({ name: 'valid.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({version:1, records:[{name:'<img src=x onerror=alert(1)>',query:'filetype:pdf'}, {name:'duplicate',query:expected}]})) });
    await page.waitForFunction(() => document.getElementById('status').textContent.startsWith('1 kayıt eklendi'));
    assert.equal(await page.locator('#savedList .dork-item').count(), before + 1); assert.equal(await page.locator('#savedList img').count(), 0);
    const downloadPromise = page.waitForEvent('download'); await page.locator('#exportBtn').click();
    const download = await downloadPromise; assert.equal(download.suggestedFilename(), 'dorkcraft-kayitlar.json');
    const stream = await download.createReadStream(); let contents = ''; for await (const chunk of stream) contents += chunk;
    assert.equal(JSON.parse(contents).records.length, before + 1);
    await page.locator('[data-tab="templates"]').click(); await page.locator('#templateSearch').fill('no-such-template-zz');
    assert.match(await page.locator('#templateCount').innerText(), /Eşleşen şablon yok/);
    await page.locator('#templateSearch').fill(''); await page.locator('#categoryFilter').selectOption({index:1});
    assert.equal(await page.locator('.cat-card').count(), 1);
    await page.locator('.cat-card').getByRole('button', {name:'düzenle',exact:true}).first().click(); assert.equal(await page.locator('#customInput').inputValue(), 'intitle:"index of" /');
    await page.locator('[data-tab="builder"]').click(); await page.locator('#scope').fill('example..com');
    assert.equal(await page.locator('#searchBtn').isDisabled(), true);
    await page.locator('#scope').fill('example.com');
    await page.locator('#addRowBtn').click(); await page.locator('#opRows .input').last().fill('annual report');
    await page.locator('#opRows .negate').last().click(); assert.match(await page.locator('#outputBox').innerText(), /-inurl:"annual report"/);
    await page.locator('#opRows .row-toggle').last().uncheck(); assert.doesNotMatch(await page.locator('#outputBox').innerText(), /inurl:/);
    const ids = await page.locator('[id]').evaluateAll(els => els.map(el => el.id)); assert.equal(new Set(ids).size, ids.length);
    if (process.env.SCREENSHOT_DIR) await page.screenshot({path:`${process.env.SCREENSHOT_DIR}/desktop.png`,fullPage:true});
    await page.setViewportSize({width:375,height:812});
    for (const tab of ['builder','custom','templates','library','reference']) {
      await page.locator(`[data-tab="${tab}"]`).click();
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `${tab} mobile overflow`);
    }
    await page.locator('[data-tab="builder"]').click();
    if (process.env.SCREENSHOT_DIR) await page.screenshot({path:`${process.env.SCREENSHOT_DIR}/mobile.png`,fullPage:true});
    const blocked = await browser.newContext();
    await blocked.addInitScript(() => { Storage.prototype.setItem = () => { throw new DOMException('blocked'); }; Storage.prototype.getItem = () => { throw new DOMException('blocked'); }; });
    const blockedPage = await blocked.newPage(); await blockedPage.goto(process.env.APP_URL || 'http://127.0.0.1:8765');
    await blockedPage.locator('#keywords').fill('works without storage'); assert.match(await blockedPage.locator('#outputBox').innerText(), /works without storage/);
    assert.deepEqual(errors, []);
    console.log('PASS: builder, custom actions, scope, persistence, library, history, JSON atomic import/export, XSS, template filters, row controls, mobile layout, unavailable storage.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
